// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace BuildGameplayTags
{
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_BadDefinition);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_Occupied);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_NoSupport);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_NoResource);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_Blocked);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_LimitReached);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_NotFound);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_WouldOrphan);
	BUILDINGCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_TooFar);
}
