"""Import and configure only the compact, non-buildable emergency life raft.

This is the focused entry point for regenerating:

    /Raft/Vehicles/LifeRaft/SM_LifeRaft
    /Raft/Vehicles/LifeRaft/DA_Raft_LifeRaft
    /Raft/Vehicles/LifeRaft/BP_Raft_LifeRaft

It deliberately does not build the deck cannon, naval build pieces, helm, or vessel
component Blueprints.  Run the full CreateRaftNavalAssets.py pipeline only when those
dependencies (including /NavalCore/Naval/BP_Naval_Cannon) are available.

Prerequisites:

* RaftRuntime is compiled and loaded.
* /Raft/Vehicles/Raft/DA_Raft_Default exists.
* blender/models/SM_LifeRaft.fbx was generated by SM_LifeRaft.py.
"""

from pathlib import Path
import runpy

import unreal


PROJECT_ROOT = Path(unreal.Paths.project_dir()).resolve()
RAFT_PYTHON = PROJECT_ROOT / "Plugins" / "GameFeatures" / "Raft" / "Content" / "Python"
NAVAL_ASSET_SCRIPT = RAFT_PYTHON / "CreateRaftNavalAssets.py"


def require(value, message):
    if not value:
        raise RuntimeError(message)
    return value


def main():
    require(
        NAVAL_ASSET_SCRIPT.is_file(),
        f"Missing shared Raft asset library: {NAVAL_ASSET_SCRIPT}",
    )
    unreal.AssetRegistryHelpers.get_asset_registry().scan_paths_synchronous(
        ["/Raft"], True, True
    )

    # Load the full script as a function library under a non-main name.  Its main()
    # function is therefore not executed, so missing cannon/helm assets cannot block
    # this focused life-raft regeneration pass.
    library = runpy.run_path(
        str(NAVAL_ASSET_SCRIPT), run_name="raft_naval_asset_library"
    )
    configure_life_raft = require(
        library.get("configure_life_raft"),
        f"configure_life_raft is missing from {NAVAL_ASSET_SCRIPT}",
    )
    configure_life_raft()
    unreal.log(
        "[RaftLifeRaftAssets] PASS: regenerated SM/DA/BP under "
        "/Raft/Vehicles/LifeRaft without running naval-cannon generation"
    )


if __name__ == "__main__":
    main()
