# DO NOT EDIT — generated by /new-building Foundation
# BuildableId : Foundation
# Type        : floor  (地基 — 水平厚板，带凸起边框)
# Dimensions  : W=300cm  D=300cm  H=25cm  (Blender: 3.0m × 3.0m × 0.25m)
# Placement   : can_ground=True  can_floor=True
# Description : 可放置在任何地表的建造地基，带 5cm 凸起边框增加可视辨识度

import bpy
import bmesh
import math

# ── 清场 ─────────────────────────────────────────────────────────────────────
for obj in list(bpy.data.objects):
    bpy.data.objects.remove(obj, do_unlink=True)
for act in list(bpy.data.actions):
    bpy.data.actions.remove(act)
for mat in list(bpy.data.materials):
    if mat.users == 0:
        bpy.data.materials.remove(mat)

# ── 材质工具 ──────────────────────────────────────────────────────────────────
def get_bsdf(mat):
    for node in mat.node_tree.nodes:
        if node.type == 'BSDF_PRINCIPLED':
            return node
    return None

def make_material(name, color, metallic=0.0, roughness=0.85, alpha=1.0):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = get_bsdf(mat)
    if bsdf is None:
        return mat
    base = bsdf.inputs.get("Base Color") or bsdf.inputs.get("Color")
    if base:
        base.default_value = (*color, 1.0)
    m = bsdf.inputs.get("Metallic")
    if m:
        m.default_value = metallic
    r = bsdf.inputs.get("Roughness")
    if r:
        r.default_value = roughness
    return mat

# ── 尺寸（Blender 米，1 UE5 cm = 0.01 m）────────────────────────────────────
W    = 3.0    # 宽  300 cm
D    = 3.0    # 深  300 cm
H    = 0.20   # 主体厚度  20 cm
LIP  = 0.05   # 凸起边框宽度   5 cm
LH   = 0.05   # 凸起边框高度   5 cm（使总高度为 25 cm）

# ── 建模 ─────────────────────────────────────────────────────────────────────
def main():
    mat_foundation = make_material(
        "M_Foundation",
        color=(0.55, 0.54, 0.51),   # 混凝土灰
        roughness=0.88,
    )
    mat_edge = make_material(
        "M_Foundation_Edge",
        color=(0.48, 0.47, 0.44),   # 边框略深，增加视觉层次
        roughness=0.80,
    )

    # ── 零件 1：主体平板 (300 × 300 × 20 cm) ─────────────────────────────
    bpy.ops.mesh.primitive_cube_add(location=(0.0, 0.0, H / 2))
    slab = bpy.context.object
    slab.name = "Foundation_Slab"
    slab.data.name = "Foundation_Slab_Mesh"
    slab.scale = (W / 2, D / 2, H / 2)
    bpy.ops.object.transform_apply(scale=True, location=False, rotation=False)
    slab.data.materials.append(mat_foundation)

    # ── 零件 2～5：四侧凸起边框 ───────────────────────────────────────────
    # 每条边框 = 长条矩形，沿主板顶面凸起
    border_top_z = H + LH / 2   # 边框中心 Z

    # 参数：(中心X, 中心Y, 长度X, 长度Y)
    border_specs = [
        # 前 (+Y)
        ( 0.0,    (D / 2 - LIP / 2),  W,  LIP),
        # 后 (-Y)
        ( 0.0,   -(D / 2 - LIP / 2),  W,  LIP),
        # 左 (-X)
        (-(W / 2 - LIP / 2),  0.0,  LIP,  D - LIP * 2),
        # 右 (+X)
        ( (W / 2 - LIP / 2),  0.0,  LIP,  D - LIP * 2),
    ]

    border_pieces = []
    for i, (cx, cy, lx, ly) in enumerate(border_specs):
        bpy.ops.mesh.primitive_cube_add(location=(cx, cy, border_top_z))
        b = bpy.context.object
        b.name = f"Foundation_Border_{i}"
        b.data.name = f"Foundation_Border_{i}_Mesh"
        b.scale = (lx / 2, ly / 2, LH / 2)
        bpy.ops.object.transform_apply(scale=True, location=False, rotation=False)
        b.data.materials.append(mat_edge)
        border_pieces.append(b)

    # ── 合并为单一网格 ────────────────────────────────────────────────────
    bpy.ops.object.select_all(action='DESELECT')
    for piece in border_pieces:
        piece.select_set(True)
    slab.select_set(True)
    bpy.context.view_layer.objects.active = slab
    bpy.ops.object.join()

    merged = bpy.context.object
    merged.name = "SM_Foundation"
    merged.data.name = "SM_Foundation_Mesh"

    # ── UV 展开 ───────────────────────────────────────────────────────────
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.uv.smart_project(angle_limit=66.0, island_margin=0.02)
    bpy.ops.object.mode_set(mode='OBJECT')

    # 确保导出前处于 OBJECT 模式，并将合并后对象标记以便 run() 找到
    bpy.ops.object.select_all(action='DESELECT')
    merged.select_set(True)
    bpy.context.view_layer.objects.active = merged

    vert_count = len(merged.data.vertices)
    print(f"[合并结果] 顶点数: {vert_count}  多边形数: {len(merged.data.polygons)}")
    if vert_count == 0:
        print("[错误] 合并后网格为空，请检查 join() 上下文")


# ── 注入 3D 视口上下文（仅用于建模 ops，导出在外部执行）──────────────────
# FBX 导出器不需要 VIEW_3D 上下文；在 temp_override 内部调用会导致部分
# Blender 版本（4.1+）只写入材质数据而丢失网格几何体。
def run():
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                for region in area.regions:
                    if region.type == 'WINDOW':
                        with bpy.context.temp_override(
                            window=window, area=area, region=region
                        ):
                            main()   # 建模 + UV，export 不在此处
                        break

    # ── FBX 导出（在 temp_override 范围外执行）──────────────────────────
    merged = bpy.data.objects.get("SM_Foundation")
    if merged is None:
        raise RuntimeError("SM_Foundation 对象未找到，main() 可能未正常执行")

    bpy.ops.object.select_all(action='DESELECT')
    merged.select_set(True)
    bpy.context.view_layer.objects.active = merged

    export_path = "C:/EpicWkspc/LyraStarterGame/blender/fbx/SM_Foundation.fbx"
    bpy.ops.export_scene.fbx(
        filepath=export_path,
        use_selection=True,
        global_scale=1.0,
        apply_scale_options='FBX_SCALE_UNITS',   # m→cm 烘焙进几何体坐标，不乘 100
        axis_forward='-Z',
        axis_up='Y',
        object_types={'MESH'},
        bake_anim=False,
        path_mode='AUTO',
    )

    import os
    size_kb = os.path.getsize(export_path) // 1024
    print(f"SM_Foundation 导出完成: {export_path}")
    print(f"  文件大小: {size_kb} KB  （＜5KB 说明几何体仍为空）")
    print(f"  尺寸（UE5 cm）: W=300  D=300  H=25（主板 20 + 凸框 5）")
    print(f"  材质数: 2（M_Foundation + M_Foundation_Edge）")


run()
