# DO NOT EDIT — generated by /new-building Wall
# BuildableId : Wall
# Type        : wall
# Dimensions  : W=200cm  H=300cm  D=15cm  (Blender: 2.0m × 3.0m × 0.15m)
# Placement   : can_ground=True

import bpy
import math

# ── 清场（直接 API，不走 bpy.ops，无需视口上下文）────────────────────────
for obj in list(bpy.data.objects):
    bpy.data.objects.remove(obj, do_unlink=True)
for mat in list(bpy.data.materials):
    if mat.users == 0:
        bpy.data.materials.remove(mat)

# ── 材质工具函数 ─────────────────────────────────────────────────────────
def get_bsdf(mat):
    for node in mat.node_tree.nodes:
        if node.type == 'BSDF_PRINCIPLED':
            return node
    return None

def make_material(name, color, metallic=0.0, roughness=0.6, alpha=1.0):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = get_bsdf(mat)
    if bsdf is None:
        return mat
    base = bsdf.inputs.get("Base Color") or bsdf.inputs.get("Color")
    if base:
        base.default_value = (*color, 1.0)
    m = bsdf.inputs.get("Metallic")
    if m:
        m.default_value = metallic
    r = bsdf.inputs.get("Roughness")
    if r:
        r.default_value = roughness
    if alpha < 1.0:
        a = bsdf.inputs.get("Alpha")
        if a:
            a.default_value = alpha
        try:
            mat.blend_method = 'BLEND'
        except AttributeError:
            pass
    return mat

# ── 建模 ─────────────────────────────────────────────────────────────────
# Wall：宽(X)=2.0m，高(Z)=3.0m，厚(Y)=0.15m
# Blender cube 默认为 ±1 单位，需要 scale / 2
W_m  = 2.0     # 200 cm
H_m  = 3.0     # 300 cm
D_m  = 0.15    # 15 cm

def main():
    mat_wall = make_material("M_Wall", (0.82, 0.76, 0.68), roughness=0.7)

    # 主墙体
    bpy.ops.mesh.primitive_cube_add(location=(0.0, 0.0, H_m / 2))
    wall = bpy.context.object
    wall.name = "SM_Wall"
    wall.data.name = "SM_Wall_Mesh"
    wall.scale = (W_m / 2, D_m / 2, H_m / 2)
    wall.data.materials.append(mat_wall)

    # 应用 scale（导出前必须应用，否则 FBX 里是 scale 而非真实顶点坐标）
    bpy.ops.object.select_all(action='DESELECT')
    wall.select_set(True)
    bpy.context.view_layer.objects.active = wall
    bpy.ops.object.transform_apply(scale=True, location=False, rotation=False)

    # UV 展开
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.uv.smart_project(angle_limit=66.0, island_margin=0.02)
    bpy.ops.object.mode_set(mode='OBJECT')

    # FBX 导出
    export_path = "C:/EpicWkspc/LyraStarterGame/blender/fbx/SM_Wall.fbx"
    bpy.ops.export_scene.fbx(
        filepath=export_path,
        use_selection=True,
        global_scale=1.0,
        apply_scale_options='FBX_SCALE_UNITS',   # m → cm 烘焙进几何体，不乘 100
        axis_forward='-Z',
        axis_up='Y',
        object_types={'MESH'},
        bake_anim=False,
        path_mode='AUTO',
    )

    print(f"SM_Wall 导出完成: {export_path}")
    print(f"  尺寸（UE5 cm）: W=200  H=300  D=15")


# ── 注入 3D 视口上下文（解决 poll() context is incorrect）────────────────
def run():
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                for region in area.regions:
                    if region.type == 'WINDOW':
                        with bpy.context.temp_override(
                            window=window, area=area, region=region
                        ):
                            main()
                        return
    raise RuntimeError("未找到 3D 视口，请确认 Scripting 工作区包含 3D 视口面板")


run()
