// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace NavalGameplayTags
{
	// Message channels. Everything the HUD, audio and the match rules need arrives here;
	// the framework never unicasts a Client RPC for feedback.
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Vessel_State);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Vessel_Load);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Vessel_Part);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Vessel_Helm);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Vessel_Alert);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Shot_Blocked);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HeavyWeapon_State);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Projectile_Impact);

	// Alerts carried inside FNavalAlertMessage.
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alert_Boarded);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alert_CoreContested);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alert_DangerousDraft);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alert_Foundering);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alert_HeavyWeaponDeploying);

	// Refusal reasons. Callers surface exactly one, matching the design's "show a single
	// main reason" rule for build and interaction failures.
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_SevereOverload);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_NotOperational);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_WrongTeam);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_SeatOccupied);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_MinimumRange);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_MuzzleBlocked);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_UnderConstruction);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_Reloading);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_RepairLocked);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_RepairSpent);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_TooFar);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_GroundUnsuitable);
	NAVALCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fail_LimitReached);
}
