// Copyright Epic Games, Inc. All Rights Reserved.

#if WITH_DEV_AUTOMATION_TESTS

#include "HAL/FileManager.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/AutomationTest.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Terrain/OceanTerrainBiome.h"
#include "Terrain/OceanTerrainContent.h"
#include "Terrain/OceanTerrainMeshBuilder.h"
#include "Terrain/OceanTerrainOutline.h"
#include "Terrain/OceanTerrainWater.h"

#include "../OceanTerrainHash.h"

/**
 * Cell-for-cell comparison against the reference implementation.
 *
 * The fixture is generated by SkyLand's scripts/export-terrain-parity.mjs and must be
 * regenerated, never hand-edited, whenever the reference terrain changes.
 *
 * This test exists because of how the failure it catches presents. Get one shift, one
 * threshold, or one salt wrong in the port and the terrain still looks like terrain -- it is
 * simply a different world from the one the other end generates. Without a fixture that
 * error surfaces as a player standing inside a hill or floating above one, and working back
 * from that symptom to a mistyped constant is close to impossible.
 *
 * The three layers are checked separately on purpose. If the hash probes fail, nothing below
 * them is worth reading; if only the biome grid fails, the height thresholds are fine and the
 * fault is in the Voronoi or the climate table.
 */
namespace
{
	struct FParityFixture
	{
		int32 CellMinimum = 0;
		int32 CellMaximum = 0;

		struct FHashProbe
		{
			uint32 Seed;
			int32 A;
			int32 B;
			int32 C;
			uint32 Expected;
		};

		struct FNoiseProbe
		{
			uint32 Seed;
			int32 X;
			int32 Y;
			int32 Shift;
			int32 Expected;
		};

		struct FGrid
		{
			uint32 Seed = 0;
			TArray<int32> Values;
		};

		TArray<FHashProbe> HashProbes;
		TArray<FNoiseProbe> NoiseProbes;
		TArray<FGrid> BiomeGrids;
		TArray<FGrid> CellGrids;

		int32 Span() const { return CellMaximum - CellMinimum + 1; }
	};

	FString FixturePath()
	{
		const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("OceanCore"));
		if (!Plugin.IsValid())
		{
			return FString();
		}
		return FPaths::Combine(
			Plugin->GetBaseDir(),
			TEXT("Source/OceanCoreRuntime/Private/Terrain/Tests/Fixtures/terrain-parity.txt"));
	}

	uint32 ParseSeed(const FString& Token)
	{
		return static_cast<uint32>(FCString::Strtoui64(*Token, nullptr, 10));
	}

	int32 ParseSigned(const FString& Token)
	{
		return static_cast<int32>(FCString::Atoi64(*Token));
	}

	bool ParseGridRows(
		const TArray<FString>& Lines,
		int32& LineIndex,
		int32 Span,
		TArray<int32>& OutValues,
		FString& OutError)
	{
		OutValues.Reset(Span * Span);
		for (int32 Row = 0; Row < Span; ++Row)
		{
			if (!Lines.IsValidIndex(LineIndex))
			{
				OutError = FString::Printf(TEXT("fixture ended after %d of %d grid rows"), Row, Span);
				return false;
			}
			TArray<FString> Tokens;
			Lines[LineIndex++].ParseIntoArray(Tokens, TEXT(" "), true);
			if (Tokens.Num() != Span)
			{
				OutError = FString::Printf(
					TEXT("grid row %d has %d entries, expected %d"), Row, Tokens.Num(), Span);
				return false;
			}
			for (const FString& Token : Tokens)
			{
				OutValues.Add(static_cast<int32>(FCString::Strtoui64(*Token, nullptr, 16)));
			}
		}
		return true;
	}

	bool LoadFixture(FParityFixture& Out, FString& OutError)
	{
		const FString Path = FixturePath();
		if (Path.IsEmpty())
		{
			OutError = TEXT("plugin OceanCore not found, cannot locate the parity fixture");
			return false;
		}

		FString Contents;
		if (!FFileHelper::LoadFileToString(Contents, *Path))
		{
			OutError = FString::Printf(TEXT("cannot read parity fixture at %s"), *Path);
			return false;
		}

		TArray<FString> RawLines;
		Contents.ParseIntoArrayLines(RawLines, false);

		TArray<FString> Lines;
		Lines.Reserve(RawLines.Num());
		for (FString& Line : RawLines)
		{
			Line.TrimStartAndEndInline();
			if (Line.IsEmpty() || Line.StartsWith(TEXT("#")))
			{
				continue;
			}
			Lines.Add(MoveTemp(Line));
		}

		for (int32 LineIndex = 0; LineIndex < Lines.Num();)
		{
			TArray<FString> Tokens;
			Lines[LineIndex++].ParseIntoArray(Tokens, TEXT(" "), true);
			if (Tokens.Num() == 0)
			{
				continue;
			}

			const FString& Keyword = Tokens[0];
			if (Keyword == TEXT("cellMin") && Tokens.Num() >= 2)
			{
				Out.CellMinimum = ParseSigned(Tokens[1]);
			}
			else if (Keyword == TEXT("cellMax") && Tokens.Num() >= 2)
			{
				Out.CellMaximum = ParseSigned(Tokens[1]);
			}
			else if (Keyword == TEXT("hash") && Tokens.Num() >= 6)
			{
				Out.HashProbes.Add({
					ParseSeed(Tokens[1]),
					ParseSigned(Tokens[2]),
					ParseSigned(Tokens[3]),
					ParseSigned(Tokens[4]),
					static_cast<uint32>(FCString::Strtoui64(*Tokens[5], nullptr, 16)) });
			}
			else if (Keyword == TEXT("noise") && Tokens.Num() >= 6)
			{
				Out.NoiseProbes.Add({
					ParseSeed(Tokens[1]),
					ParseSigned(Tokens[2]),
					ParseSigned(Tokens[3]),
					ParseSigned(Tokens[4]),
					ParseSigned(Tokens[5]) });
			}
			else if ((Keyword == TEXT("biome") || Keyword == TEXT("cell")) && Tokens.Num() >= 2)
			{
				FParityFixture::FGrid Grid;
				Grid.Seed = ParseSeed(Tokens[1]);
				if (!ParseGridRows(Lines, LineIndex, Out.Span(), Grid.Values, OutError))
				{
					return false;
				}
				if (Keyword == TEXT("biome"))
				{
					Out.BiomeGrids.Add(MoveTemp(Grid));
				}
				else
				{
					Out.CellGrids.Add(MoveTemp(Grid));
				}
			}
		}

		if (Out.Span() <= 0 || Out.CellGrids.Num() == 0)
		{
			OutError = TEXT("parity fixture parsed but carries no cell grid");
			return false;
		}
		return true;
	}
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FOceanTerrainParityTest,
	"OceanCore.Terrain.Parity",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FOceanTerrainParityTest::RunTest(const FString& Parameters)
{
	FParityFixture Fixture;
	FString Error;
	if (!LoadFixture(Fixture, Error))
	{
		AddError(Error);
		return false;
	}

	for (const FParityFixture::FHashProbe& Probe : Fixture.HashProbes)
	{
		const uint32 Actual = OceanTerrain::Hash32(Probe.Seed, Probe.A, Probe.B, Probe.C);
		if (Actual != Probe.Expected)
		{
			AddError(FString::Printf(
				TEXT("Hash32(%u, %d, %d, %d) = %08x, expected %08x"),
				Probe.Seed, Probe.A, Probe.B, Probe.C, Actual, Probe.Expected));
			// One wrong mixer makes every value below it wrong; reporting thousands of
			// downstream mismatches would bury the one line that matters.
			return false;
		}
	}

	for (const FParityFixture::FNoiseProbe& Probe : Fixture.NoiseProbes)
	{
		const int32 Actual = OceanTerrain::ValueNoise(Probe.Seed, Probe.X, Probe.Y, Probe.Shift);
		if (Actual != Probe.Expected)
		{
			AddError(FString::Printf(
				TEXT("ValueNoise(%u, %d, %d, %d) = %d, expected %d"),
				Probe.Seed, Probe.X, Probe.Y, Probe.Shift, Actual, Probe.Expected));
			return false;
		}
	}

	const int32 Span = Fixture.Span();
	constexpr int32 MaximumReportedMismatches = 8;

	for (const FParityFixture::FGrid& Grid : Fixture.BiomeGrids)
	{
		int32 Mismatches = 0;
		for (int32 Row = 0; Row < Span; ++Row)
		{
			for (int32 Column = 0; Column < Span; ++Column)
			{
				const int32 CellX = Fixture.CellMinimum + Column;
				const int32 CellY = Fixture.CellMinimum + Row;
				const int32 Expected = Grid.Values[Row * Span + Column];
				const int32 Actual = static_cast<int32>(OceanTerrain::BiomeAt(Grid.Seed, CellX, CellY));
				if (Actual != Expected)
				{
					if (++Mismatches <= MaximumReportedMismatches)
					{
						AddError(FString::Printf(
							TEXT("BiomeAt(%u, %d, %d) = %d, expected %d"),
							Grid.Seed, CellX, CellY, Actual, Expected));
					}
				}
			}
		}
		if (Mismatches > MaximumReportedMismatches)
		{
			AddError(FString::Printf(
				TEXT("seed %u: %d biome cells differ in total"), Grid.Seed, Mismatches));
		}
	}

	for (const FParityFixture::FGrid& Grid : Fixture.CellGrids)
	{
		int32 Mismatches = 0;
		for (int32 Row = 0; Row < Span; ++Row)
		{
			for (int32 Column = 0; Column < Span; ++Column)
			{
				const int32 CellX = Fixture.CellMinimum + Column;
				const int32 CellY = Fixture.CellMinimum + Row;
				const int32 Expected = Grid.Values[Row * Span + Column];
				const int32 Actual = OceanTerrain::CellCodeAt(Grid.Seed, CellX, CellY);
				if (Actual != Expected)
				{
					if (++Mismatches <= MaximumReportedMismatches)
					{
						AddError(FString::Printf(
							TEXT("CellCodeAt(%u, %d, %d) = %04x (h=%d s=%d b=%d shape=%d), ")
							TEXT("expected %04x (h=%d s=%d b=%d shape=%d)"),
							Grid.Seed, CellX, CellY,
							Actual,
							OceanTerrain::CellHeightLevel(Actual),
							static_cast<int32>(OceanTerrain::CellSurface(Actual)),
							static_cast<int32>(OceanTerrain::CellBiome(Actual)),
							static_cast<int32>(OceanTerrain::CellShape(Actual)),
							Expected,
							OceanTerrain::CellHeightLevel(Expected),
							static_cast<int32>(OceanTerrain::CellSurface(Expected)),
							static_cast<int32>(OceanTerrain::CellBiome(Expected)),
							static_cast<int32>(OceanTerrain::CellShape(Expected))));
					}
				}
			}
		}
		if (Mismatches > MaximumReportedMismatches)
		{
			AddError(FString::Printf(
				TEXT("seed %u: %d cells differ in total"), Grid.Seed, Mismatches));
		}
	}

	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FOceanTerrainCellCodeTest,
	"OceanCore.Terrain.CellCode",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FOceanTerrainCellCodeTest::RunTest(const FString& Parameters)
{
	using namespace OceanTerrain;

	// Sign extension is the one decode that silently produces a legal-looking answer: without
	// it, level -1 reads back as 255 and the cell lands 255 metres up instead of one down.
	for (int32 Level = MinimumHeightLevel; Level <= MaximumHeightLevel; ++Level)
	{
		const int32 Code = EncodeCell(
			Level, EOceanTerrainSurface::Water, EOceanTerrainShape::RampWest, EOceanTerrainBiome::Snow);
		TestEqual(TEXT("height round-trips"), CellHeightLevel(Code), Level);
		TestTrue(TEXT("code fits sixteen bits"), Code >= 0 && Code <= 0xFFFF);
	}

	// Every field has to survive the others being set; a shift that overlaps shows up here
	// rather than as one biome quietly changing when a cell is raised.
	for (int32 ShapeIndex = 0; ShapeIndex < ShapeCount; ++ShapeIndex)
	{
		for (int32 BiomeIndex = 0; BiomeIndex < BiomeCount; ++BiomeIndex)
		{
			for (int32 SurfaceIndex = 0; SurfaceIndex <= 1; ++SurfaceIndex)
			{
				const EOceanTerrainShape Shape = static_cast<EOceanTerrainShape>(ShapeIndex);
				const EOceanTerrainBiome Biome = static_cast<EOceanTerrainBiome>(BiomeIndex);
				const EOceanTerrainSurface Surface = static_cast<EOceanTerrainSurface>(SurfaceIndex);
				const int32 Code = EncodeCell(-3, Surface, Shape, Biome);
				TestEqual(TEXT("shape round-trips"), static_cast<int32>(CellShape(Code)), ShapeIndex);
				TestEqual(TEXT("biome round-trips"), static_cast<int32>(CellBiome(Code)), BiomeIndex);
				TestEqual(TEXT("surface round-trips"), static_cast<int32>(CellSurface(Code)), SurfaceIndex);
				TestEqual(TEXT("height round-trips"), CellHeightLevel(Code), -3);
			}
		}
	}

	// A sea bed is water and flat; the spawn area is reserved flat ground. Both are properties
	// the generator promises, not incidental results.
	constexpr uint32 Seed = 0x5c1a2d0b;
	for (int32 CellY = -5; CellY <= 5; ++CellY)
	{
		for (int32 CellX = -5; CellX <= 5; ++CellX)
		{
			const int32 Code = CellCodeAt(Seed, CellX, CellY);
			TestEqual(TEXT("spawn area is level zero"), CellHeightLevel(Code), 0);
			TestEqual(TEXT("spawn area is flat"), static_cast<int32>(CellShape(Code)), 0);
			TestEqual(
				TEXT("spawn area is dry"),
				static_cast<int32>(CellSurface(Code)),
				static_cast<int32>(EOceanTerrainSurface::Ground));
		}
	}

	// Surface sampling has to agree with the corner heights the mesh will be built from, or
	// the ground the player walks on is not the ground that was drawn.
	for (int32 ShapeIndex = 0; ShapeIndex < ShapeCount; ++ShapeIndex)
	{
		const EOceanTerrainShape Shape = static_cast<EOceanTerrainShape>(ShapeIndex);
		const int32 Code = EncodeCell(
			1, EOceanTerrainSurface::Ground, Shape, EOceanTerrainBiome::Grassland);
		// The lambda is named first on purpose: TFunctionRef stores a reference to the
		// callable, so binding it to a temporary would dangle immediately.
		auto CodeLookup = [Code](int32, int32) { return Code; };
		const TFunctionRef<int32(int32, int32)> Override(CodeLookup);
		for (int32 CornerY = 0; CornerY <= 1; ++CornerY)
		{
			for (int32 CornerX = 0; CornerX <= 1; ++CornerX)
			{
				// Step just inside the corner: exactly on the far edge the sample belongs to the
				// next cell, which the override would answer for anyway but the local coordinate
				// would not.
				constexpr double Inset = 0.001;
				const double LocalX = CornerX == 0 ? Inset : 1.0 - Inset;
				const double LocalY = CornerY == 0 ? Inset : 1.0 - Inset;
				const FTerrainSample Sample = SampleTerrain(
					Seed, LocalX * CellSize, LocalY * CellSize, &Override);
				const double Expected = CellCornerHeight(Code, CornerX, CornerY);
				TestTrue(
					FString::Printf(
						TEXT("shape %d corner (%d,%d): sampled %.3f, corner %.3f"),
						ShapeIndex, CornerX, CornerY, Sample.GroundZ, Expected),
					FMath::Abs(Sample.GroundZ - Expected) < HeightStep * 0.01);
			}
		}
	}

	// Water is "part of a connected body of water", never "below sea level". A dry hollow has
	// to stay dry, or digging a pit fills it by itself.
	{
		const int32 DryHollow = EncodeCell(
			-3, EOceanTerrainSurface::Ground, EOceanTerrainShape::Flat, EOceanTerrainBiome::Mud);
		FTerrainSample Sample;
		Sample.Code = DryHollow;
		Sample.Surface = CellSurface(DryHollow);
		Sample.GroundZ = CellTopHeight(DryHollow);
		TestEqual(TEXT("a dry hollow below sea level holds no water"), WaterDepth(Sample, 0.0), 0.0);
		TestFalse(TEXT("a dry hollow is not flooded"), SampleHasWater(Sample, 0.0));
		TestFalse(TEXT("a dry hollow needs no water surface"), CellHasWater(DryHollow, 0.0));

		const int32 SeaBed = EncodeCell(
			-3, EOceanTerrainSurface::Water, EOceanTerrainShape::Flat, EOceanTerrainBiome::Mud);
		Sample.Code = SeaBed;
		Sample.Surface = CellSurface(SeaBed);
		TestEqual(TEXT("sea bed is three levels deep"), WaterDepth(Sample, 0.0), 3.0 * HeightStep);
		TestTrue(TEXT("sea bed needs a water surface"), CellHasWater(SeaBed, 0.0));
	}

	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FOceanTerrainOutlineTest,
	"OceanCore.Terrain.Outline",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FOceanTerrainOutlineTest::RunTest(const FString& Parameters)
{
	using namespace OceanTerrain;

	const auto MakeCell = [](int32 Level, EOceanTerrainShape Shape)
	{
		return EncodeCell(Level, EOceanTerrainSurface::Ground, Shape, EOceanTerrainBiome::Grassland);
	};

	// Top faces point up, and a cell is folded exactly when it is a corner shape. Flat and the
	// four ramps stay planar -- that is why the fill mesh needs no interior line on them.
	for (int32 ShapeIndex = 0; ShapeIndex < ShapeCount; ++ShapeIndex)
	{
		const EOceanTerrainShape Shape = static_cast<EOceanTerrainShape>(ShapeIndex);
		const int32 Code = MakeCell(0, Shape);
		const FVector First = CellTriangleNormal(Code, 0);
		const FVector Second = CellTriangleNormal(Code, 1);
		TestTrue(FString::Printf(TEXT("shape %d first normal faces up"), ShapeIndex), First.Z > 0.0);
		TestTrue(FString::Printf(TEXT("shape %d second normal faces up"), ShapeIndex), Second.Z > 0.0);

		const bool bFolded = !First.Equals(Second, 1.0e-6);
		TestEqual(
			FString::Printf(TEXT("shape %d fold matches the corner test"), ShapeIndex),
			bFolded,
			CellDiagonalIsCrease(Code));
	}

	// Two identical flat cells share a plane, so there is nothing to draw between them. This is
	// the case that must stay None: if it inks, every flat field turns into graph paper.
	{
		const int32 Flat = MakeCell(0, EOceanTerrainShape::Flat);
		for (int32 DirectionIndex = 0; DirectionIndex < 4; ++DirectionIndex)
		{
			const ECellDirection Direction = static_cast<ECellDirection>(DirectionIndex);
			TestEqual(
				TEXT("flat meeting flat draws nothing"),
				static_cast<int32>(EdgeInkBetween(Flat, Flat, Direction)),
				static_cast<int32>(EEdgeInk::None));
		}
	}

	// A ramp climbing north meets the plateau above it along its north edge with no height
	// break, but the slope changes: that is a fold, and it is the line the inverted hull cannot
	// produce.
	{
		const int32 Ramp = MakeCell(0, EOceanTerrainShape::RampNorth);
		const int32 Plateau = MakeCell(1, EOceanTerrainShape::Flat);
		TestEqual(
			TEXT("ramp into its plateau is a fold"),
			static_cast<int32>(EdgeInkBetween(Ramp, Plateau, ECellDirection::North)),
			static_cast<int32>(EEdgeInk::Fold));
		TestEqual(
			TEXT("and the same edge from the other side"),
			static_cast<int32>(EdgeInkBetween(Plateau, Ramp, ECellDirection::South)),
			static_cast<int32>(EEdgeInk::Fold));
	}

	// The ramp's foot meets flat ground at the same height, but the two surfaces are not
	// coplanar -- horizontal ground against a tilted ramp. That is a fold too, and it is the
	// line that makes a ramp read as a ramp instead of as a differently shaded patch of field.
	{
		const int32 Ramp = MakeCell(0, EOceanTerrainShape::RampNorth);
		const int32 Ground = MakeCell(0, EOceanTerrainShape::Flat);
		TestEqual(
			TEXT("ramp foot meeting flat ground is a fold"),
			static_cast<int32>(EdgeInkBetween(Ramp, Ground, ECellDirection::South)),
			static_cast<int32>(EEdgeInk::Fold));
	}

	// Two identical ramps side by side share a plane, and so do two stacked into a staircase:
	// a long slope draws its two outer creases and nothing in between. If these inked, every
	// hillside would come out ruled like graph paper.
	{
		const int32 Ramp = MakeCell(0, EOceanTerrainShape::RampNorth);
		const int32 Beside = MakeCell(0, EOceanTerrainShape::RampNorth);
		const int32 Above = MakeCell(1, EOceanTerrainShape::RampNorth);
		TestEqual(
			TEXT("ramps side by side draw nothing"),
			static_cast<int32>(EdgeInkBetween(Ramp, Beside, ECellDirection::East)),
			static_cast<int32>(EEdgeInk::None));
		TestEqual(
			TEXT("ramps continuing up the slope draw nothing"),
			static_cast<int32>(EdgeInkBetween(Ramp, Above, ECellDirection::North)),
			static_cast<int32>(EEdgeInk::None));
	}

	// A one-level drop with no ramp is a vertical face: the strongest line, and the place the
	// mesh builder owes two triangles.
	{
		const int32 High = MakeCell(1, EOceanTerrainShape::Flat);
		const int32 Low = MakeCell(0, EOceanTerrainShape::Flat);
		TestEqual(
			TEXT("a step down is a cliff"),
			static_cast<int32>(EdgeInkBetween(High, Low, ECellDirection::East)),
			static_cast<int32>(EEdgeInk::Cliff));
		TestEqual(
			TEXT("seen from below it is the same cliff"),
			static_cast<int32>(EdgeInkBetween(Low, High, ECellDirection::West)),
			static_cast<int32>(EEdgeInk::Cliff));
	}

	// Each edge must be answered by the triangle that actually touches it, for both splits.
	for (int32 ShapeIndex = 0; ShapeIndex < ShapeCount; ++ShapeIndex)
	{
		const int32 Code = MakeCell(0, static_cast<EOceanTerrainShape>(ShapeIndex));
		FCellTriangle Triangles[2];
		CellTopTriangles(Code, Triangles[0], Triangles[1]);
		for (int32 DirectionIndex = 0; DirectionIndex < 4; ++DirectionIndex)
		{
			const ECellDirection Direction = static_cast<ECellDirection>(DirectionIndex);
			ECellCorner First;
			ECellCorner Second;
			CellEdgeCorners(Direction, First, Second);
			const FCellTriangle& Triangle = Triangles[CellEdgeTriangleIndex(Code, Direction)];
			const auto Contains = [&Triangle](ECellCorner Corner)
			{
				return Triangle.Corners[0] == Corner
					|| Triangle.Corners[1] == Corner
					|| Triangle.Corners[2] == Corner;
			};
			TestTrue(
				FString::Printf(
					TEXT("shape %d edge %d is owned by a triangle that touches it"),
					ShapeIndex, DirectionIndex),
				Contains(First) && Contains(Second));
		}
	}

	return !HasAnyErrors();
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FOceanTerrainMeshTest,
	"OceanCore.Terrain.Mesh",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FOceanTerrainMeshTest::RunTest(const FString& Parameters)
{
	using namespace OceanTerrain;

	constexpr uint32 Seed = 0x5c1a2d0b;
	const FTerrainPalette Palette;

	TArray<int32> Codes;
	FTerrainMeshData Mesh;
	FTerrainInkData Ink;

	for (int32 ChunkY = -1; ChunkY <= 1; ++ChunkY)
	{
		for (int32 ChunkX = -1; ChunkX <= 1; ++ChunkX)
		{
			const FIntPoint ChunkCoord(ChunkX, ChunkY);
			BuildChunkCodes(Seed, ChunkCoord, TArrayView<const int32>(), Codes);
			TestEqual(TEXT("code window is (ChunkGrid + 1) squared"), Codes.Num(), ChunkCodeSpan * ChunkCodeSpan);

			BuildChunkMesh(ChunkCoord, Codes, Palette, 0.0, Mesh);
			BuildChunkInk(ChunkCoord, Codes, Ink);

			TestTrue(TEXT("chunk produced triangles"), Mesh.TriangleCount() > 0);
			TestEqual(TEXT("one normal per vertex"), Mesh.Normals.Num(), Mesh.Positions.Num());
			TestEqual(TEXT("one colour per vertex"), Mesh.Colors.Num(), Mesh.Positions.Num());
			TestEqual(TEXT("index count is a multiple of three"), Mesh.Indices.Num() % 3, 0);

			// The projected area of the top faces has to tile the chunk exactly. This is the
			// strongest single check available here: a dropped cell, a doubled cell, and a corner
			// shape that triangulates over itself all break it, and none of them are visible in a
			// triangle count or in a screenshot.
			double ProjectedArea = 0.0;
			bool bAllNormalsValid = true;
			bool bAllCliffsVertical = true;
			bool bAllInsideChunk = true;
			for (int32 Triangle = 0; Triangle < Mesh.TriangleCount(); ++Triangle)
			{
				const int32 IndexA = static_cast<int32>(Mesh.Indices[Triangle * 3]);
				const int32 IndexB = static_cast<int32>(Mesh.Indices[Triangle * 3 + 1]);
				const int32 IndexC = static_cast<int32>(Mesh.Indices[Triangle * 3 + 2]);
				if (!Mesh.Positions.IsValidIndex(IndexA)
					|| !Mesh.Positions.IsValidIndex(IndexB)
					|| !Mesh.Positions.IsValidIndex(IndexC))
				{
					AddError(TEXT("triangle references a vertex that does not exist"));
					return false;
				}

				const FVector3f A = Mesh.Positions[IndexA];
				const FVector3f B = Mesh.Positions[IndexB];
				const FVector3f C = Mesh.Positions[IndexC];
				const FVector3f Normal = Mesh.Normals[IndexA];

				bAllNormalsValid &= FMath::IsNearlyEqual(Normal.Size(), 1.0f, 1.0e-3f);
				// Nothing may face downward: top faces point up, cliff faces stand vertical.
				bAllNormalsValid &= Normal.Z > -1.0e-3f;

				const double Cross =
					static_cast<double>(B.X - A.X) * (C.Y - A.Y)
					- static_cast<double>(B.Y - A.Y) * (C.X - A.X);
				if (Normal.Z > 0.5f)
				{
					ProjectedArea += 0.5 * Cross;
				}
				else
				{
					bAllCliffsVertical &= FMath::Abs(Normal.Z) < 1.0e-3f;
				}

				for (const FVector3f& Vertex : { A, B, C })
				{
					bAllInsideChunk &= Vertex.X >= -0.01f && Vertex.X <= ChunkSize + 0.01f;
					bAllInsideChunk &= Vertex.Y >= -0.01f && Vertex.Y <= ChunkSize + 0.01f;
				}
			}

			TestTrue(TEXT("normals are unit length and never face down"), bAllNormalsValid);
			TestTrue(TEXT("cliff faces are vertical"), bAllCliffsVertical);
			TestTrue(TEXT("vertices stay inside the chunk footprint"), bAllInsideChunk);

			const double ExpectedArea =
				static_cast<double>(ChunkGrid) * ChunkGrid * CellSize * CellSize;
			TestTrue(
				FString::Printf(
					TEXT("chunk (%d,%d) top faces tile it exactly: %.1f vs %.1f"),
					ChunkX, ChunkY, ProjectedArea, ExpectedArea),
				FMath::Abs(ProjectedArea - ExpectedArea) < 1.0);

			bool bAllSegmentsHaveLength = true;
			for (const FTerrainInkSegment& Segment : Ink.Segments)
			{
				bAllSegmentsHaveLength &= !Segment.Start.Equals(Segment.End);
			}
			TestTrue(TEXT("every ink segment has length"), bAllSegmentsHaveLength);
		}
	}

	//
	// Chunk seams. The two sides are not symmetric, and that is correct rather than a tolerance
	// to paper over: the cell that owns a cliff emits both its own lip and the neighbour's foot,
	// so the owning chunk places strictly more vertices on the shared plane. What has to hold is
	// containment -- every vertex the far chunk puts on the plane is already there. Shrink the
	// code window from ChunkGrid + 1 to ChunkGrid and the owning chunk stops knowing the
	// neighbour's heights, the feet vanish, and this is what notices.
	//
	const auto BoundaryVertices =
		[Seed, &Palette](FIntPoint ChunkCoord, int32 Axis, bool bFarSide, TSet<FIntPoint>& Out)
	{
		TArray<int32> LocalCodes;
		FTerrainMeshData LocalMesh;
		BuildChunkCodes(Seed, ChunkCoord, TArrayView<const int32>(), LocalCodes);
		BuildChunkMesh(ChunkCoord, LocalCodes, Palette, 0.0, LocalMesh);

		const float Plane = bFarSide ? ChunkSize : 0.0f;
		Out.Reset();
		for (const FVector3f& Position : LocalMesh.Positions)
		{
			const float Along = Axis == 0 ? Position.X : Position.Y;
			if (FMath::Abs(Along - Plane) >= 0.01f)
			{
				continue;
			}
			const float Across = Axis == 0 ? Position.Y : Position.X;
			Out.Add(FIntPoint(
				FMath::RoundToInt(Across * 16.0f),
				FMath::RoundToInt(Position.Z * 16.0f)));
		}
	};

	const FIntPoint Neighbours[2] = { FIntPoint(1, 0), FIntPoint(0, 1) };
	const TCHAR* AxisNames[2] = { TEXT("east/west"), TEXT("north/south") };
	for (int32 Axis = 0; Axis < 2; ++Axis)
	{
		TSet<FIntPoint> Owner;
		TSet<FIntPoint> Far;
		BoundaryVertices(FIntPoint::ZeroValue, Axis, true, Owner);
		BoundaryVertices(Neighbours[Axis], Axis, false, Far);

		TestTrue(
			FString::Printf(TEXT("%s boundary has vertices"), AxisNames[Axis]),
			Owner.Num() > 0);

		const int32 Unmatched = Far.Difference(Owner).Num();
		TestEqual(
			FString::Printf(
				TEXT("%s seam is covered: %d of %d neighbour vertices unmatched"),
				AxisNames[Axis], Unmatched, Far.Num()),
			Unmatched,
			0);
	}

	return !HasAnyErrors();
}

#endif // WITH_DEV_AUTOMATION_TESTS
